-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 22:14:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema allwaredbprueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema allwaredbprueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `allwaredbprueba` DEFAULT CHARACTER SET utf8 ;
USE `allwaredbprueba` ;

-- -----------------------------------------------------
-- Table `allwaredbprueba`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `allwaredbprueba`.`vendedor` (
  `rut` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `allwaredbprueba`.`automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `allwaredbprueba`.`automovil` (
  `patente` VARCHAR(6) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NULL,
  `vendedor_rut` VARCHAR(9) NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`patente`),
  INDEX `fk_automovil_vendedor_idx` (`vendedor_rut` ASC),
  CONSTRAINT `fk_automovil_vendedor`
    FOREIGN KEY (`vendedor_rut`)
    REFERENCES `allwaredbprueba`.`vendedor` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



CREATE USER 'userDB' IDENTIFIED BY 'userDB';

GRANT ALL ON `allwaredbprueba`.* TO 'userDB';
GRANT SELECT, INSERT, TRIGGER ON TABLE `allwaredbprueba`.* TO 'userDB';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `allwaredbprueba`.* TO 'userDB';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `allwaredbprueba`.`vendedor`
-- -----------------------------------------------------
START TRANSACTION;
USE `allwaredbprueba`;
INSERT INTO `allwaredbprueba`.`vendedor` (`rut`, `nombre`, `apellido`) VALUES ('123456789', 'Roderick', 'Veliz');
INSERT INTO `allwaredbprueba`.`vendedor` (`rut`, `nombre`, `apellido`) VALUES ('123456788', 'John', 'Doe');
INSERT INTO `allwaredbprueba`.`vendedor` (`rut`, `nombre`, `apellido`) VALUES ('123456787', 'Elisa', 'Reyes');
INSERT INTO `allwaredbprueba`.`vendedor` (`rut`, `nombre`, `apellido`) VALUES ('012345678', 'Julio', 'Pérez');
INSERT INTO `allwaredbprueba`.`vendedor` (`rut`, `nombre`, `apellido`) VALUES ('225464449', 'Antonio', 'Ramirez');
INSERT INTO `allwaredbprueba`.`vendedor` (`rut`, `nombre`, `apellido`) VALUES ('22344564k', 'Jorge', 'Morales');

COMMIT;


-- -----------------------------------------------------
-- Data for table `allwaredbprueba`.`automovil`
-- -----------------------------------------------------
START TRANSACTION;
USE `allwaredbprueba`;
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD01', 'Chevrolet', 'Aveo', 'Blanco', '123456789', 8000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD02', 'Chevrolet', 'Onix Sedan', 'Negro', '123456788', 10000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD03', 'Chevrolet', 'Aveo', 'Azul', '123456789', 8000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD04', 'Suzuki', 'Alto', 'Rojo', '123456787', 6000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD05', 'Suzuki', 'Swift', 'Plata', '012345678', 8000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD06', 'Suzuki', 'Swift', 'Blanco', '225464449', 8000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD07', 'Suzuki', 'Alto', 'Naranjo', '22344564k', 6000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD08', 'Toyota', 'Corolla', 'Blanco', '123456789', 9000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD09', 'Toyota', 'Yaris', 'Plomo', '123456788', 9000000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD10', 'Kia', 'Rio', 'Rojo', '123456788', 12500000);
INSERT INTO `allwaredbprueba`.`automovil` (`patente`, `marca`, `modelo`, `color`, `vendedor_rut`, `precio`) VALUES ('ABCD11', 'Kia', 'Morning', 'Azul', '012345678', 7800000);

COMMIT;

